import Head from 'next/head'
import Layout from '@/components/Layout'
import Hero from '@/components/Hero'
import TabsComponent from '@/components/TabsComponent'
import NeedHelp from '@/components/NeedHelp'
import News from '@/components/News'
import Testimonial from '@/components/Testimonial'


export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <TabsComponent />
        <News />
        <Testimonial />
        <NeedHelp />
      </main>
    </Layout>
  )
}
